export const amenitiesMap = new Map(Object.entries({
    "LAMP": "Abajur",
    "SHAM": "Almofada",
    "AC": "Ar Condicionado",
    "CLOTH": "Armário para Roupas",
    "VASE": "Arranjo de Flores",
    "TUB": "Banheira",
    "CHAIR": "Cadeira",
    "COFF": "Cafeteira",
    "BEDS": "Cama King Size",
    "KETT": "Chaleira Elétrica",
    "SHWR": "Chuveiro",
    "BLANK": "Cobertor Extra",
    "SAFE": "Cofre",
    "MATT": "Colchão Ortobom",
    "CUPB": "Copos",
    "BLND": "Cortinas Blackout",
    "DESK": "Escrivaninha",
    "IRON": "Ferro de Passar",
    "BOTT": "Garrafa de Água",
    "FRIDGE": "Geladeira",
    "WINDOW": "Janela com Vista",
    "TABLE": "Mesa de Café",
    "MINI": "Mini Bar",
    "BATH": "Roupão de Banho",
    "HAIR": "Secador de Cabelo",
    "SOFA": "Sofá",
    "LUGG": "Suporte para Bagagem",
    "RUG": "Tapete",
    "TELE": "Telefone",
    "TV": "Televisão",
    "LOCK": "Tranca de Segurança",
    "SLPR": "Travesseiro Extra",
    "DTV": "TV a Cabo",
    "BALC": "Varanda",
    "FAN": "Ventilador",
    "WIFI": "Wi-Fi"
}));

export const MASTER_AMENITIES_LIST_FOR_AI = Array.from(amenitiesMap.entries()).map(([code, name]) => ({ code, name }));