export const countriesMap = new Map(Object.entries({
    "AF": "Afeganistão",
    "ZA": "África do Sul",
    "DE": "Alemanha",
    "AD": "Andorra",
    "AO": "Angola",
    "SA": "Arábia Saudita",
    "AR": "Argentina",
    "AU": "Austrália",
    "AT": "Áustria",
    "BE": "Bélgica",
    "BR": "Brasil",
    "CA": "Canadá",
    "CL": "Chile",
    "CN": "China",
    "CO": "Colômbia",
    "KR": "Coreia do Sul",
    "CU": "Cuba",
    "DK": "Dinamarca",
    "EG": "Egito",
    "AE": "Emirados Árabes Unidos",
    "ES": "Espanha",
    "US": "Estados Unidos",
    "FR": "França",
    "GR": "Grécia",
    "IN": "Índia",
    "ID": "Indonésia",
    "IR": "Irã",
    "IE": "Irlanda",
    "IL": "Israel",
    "IT": "Itália",
    "JP": "Japão",
    "MX": "México",
    "NO": "Noruega",
    "NZ": "Nova Zelândia",
    "NL": "Países Baixos (Holanda)",
    "PY": "Paraguai",
    "PE": "Peru",
    "PL": "Polônia",
    "PT": "Portugal",
    "GB": "Reino Unido",
    "RU": "Rússia",
    "SE": "Suécia",
    "CH": "Suíça",
    "TR": "Turquia",
    "UA": "Ucrânia",
    "UY": "Uruguai",
    "VE": "Venezuela",
    "VN": "Vietnã"
}));