export const facilitiesMap = new Map(Object.entries({
        "POL": "Piscina",
        "SPA": "Spa",
        "BAR": "Bar",
        "RES": "Restaurante",
        "LBA": "Lounge Bar",
        "FNT": "Fonte",
        "BTS": "Banho Turco",
        "SAU": "Sauna",
        "LFT": "Lift (Elevador)",
        "PARK": "Estacionamento",
        "CST": "Castelo",
        "BLS": "Biblioteca",
        "BAL": "Balneário",
        "STU": "Estúdio",
        "JAC": "Jacuzzi",
        "TENN": "Quadra de Tênis",
        "GOLF": "Campo de Golfe",
        "BEAC": "Acesso à praia",
        "WC": "Banheiro",
        "ATM": "Caixa Eletrônico",
        "LVR": "Lavanderia",
        "RESV": "Reservatório",
        "VUE": "Vista Panorâmica",
        "GARD": "Jardim",
        "BBQ": "Churrasqueira",
        "BIC": "Bicicletário",
        "BIS": "Business Center",
        "LND": "Lanchonete",
        "RMS": "Quartos",
        "LOUN": "Lounge",
        "CONC": "Concierge",
        "RMV": "Sala de Reunião",
        "AUD": "Auditório",
        "COR": "Corredor",
        "BUS": "Ponto de ônibus",
        "WIFI": "Wi-Fi gratuito",
        "DOG": "Acomodações para animais de estimação",
        "VLT": "Valet",
        "HALL": "Hall de Entrada",
        "KDI": "Kitchenette",
        "BBS": "Bebedouro",
        "SND": "Sistema de Som",
        "VID": "Videoteca",
        "RBB": "Restaurante Buffet",
        "PLZ": "Praça de Alimentação",
        "STO": "Armazenamento",
        "DVD": "DVD/Blueray",
        "LUX": "Luxo (suites)",
        "MNW": "Mini bar",
        "BBR": "Barbecue",
        "KTV": "Karaoke",
        "CHM": "Chaminé",
        "BAS": "Basquete (Quadra)",
        "YOG": "Yoga",
        "MASS": "Massagem",
        "JMP": "Jumping (sala de trampolins)",
        "RENT": "Aluguel de veículos",
        "CLUB": "Clube Noturno",
        "CAR": "Estacionamento para Caravanas",
        "TBL": "Mesa de Bilhar",
        "POOL": "Piscina de Bolinhas (para crianças)",
        "GALA": "Gala Dinner",
        "EXPO": "Exposição",
        "CONV": "Convenção",
        "MKT": "Mercado (loja)",
        "CNF": "Confecção de roupas",
        "SMP": "Supermercado",
        "LIMO": "Limusine",
        "BMX": "Pista de BMX",
        "SKI": "Estação de Esqui",
        "BIKE": "Aluguel de Bicicleta",
        "HIK": "Trilha",
        "ADVENT": "Aventura",
        "GAD": "Galeria de Arte",
        "BOW": "Boliche",
        "VR": "Realidade Virtual",
        "ZOO": "Zoológico (ou área temática)",
        "CHUR": "Churrascaria"
}));

export const MASTER_FACILITIES_LIST_FOR_AI = Array.from(facilitiesMap.entries()).map(([code, name]) => ({ code, name }));