export const currencyMap = new Map(Object.entries({
    "USD": "Dólar Americano",
    "EUR": "Euro",
    "BRL": "Real Brasileiro",
    "GBP": "Libra Esterlina",
    "ARS": "Peso Argentino",
    "CLP": "Peso Chileno",
    "MXN": "Peso Mexicano",
    "CAD": "Dólar Canadense",
    "AUD": "Dólar Australiano",
    "NZD": "Dólar Neozelandês",
    "CHF": "Franco Suíço",
    "JPY": "Iene Japonês",
    "CNY": "Yuan Chinês",
    "HKD": "Dólar de Hong Kong",
    "SEK": "Coroa Sueca",
    "NOK": "Coroa Norueguesa",
    "DKK": "Coroa Dinamarquesa",
    "RUB": "Rublo Russo",
    "INR": "Rúpia Indiana",
    "ZAR": "Rand Sul-Africano",
    "AED": "Dirham dos Emirados Árabes Unidos",
    "SAR": "Rial Saudita",
    "TRY": "Lira Turca",
    "KRW": "Won Sul-Coreano",
    "PLN": "Złoty Polonês",
    "CZK": "Coroa Tcheca"
}));